### ISSUE TITLE
Fitness value

### ISSUE THREAD

**Issue by adilahrashid** [ahmedfgad/NeuralGenetic#2]
Hi!
Thank you for sharing this. Anyway may I know why the fitness is set to -999999999?
`fitness[max_fitness_idx] = -99999999999`
Why is it -? Wasn't fitness is based on accuracy which should be 100%?

**Comment by ahmedfgad** [comment]
Hi,
The reason is making sure that a solution selected as a parent is not selected again.
Assume that there are 4 solutions (A, B, C, and D) with their fitness values stored in the list below and we want to select only 3 solutions as parents for mating. 
[5, 2, 7, 1, 3, 1]
The element corresponding to the maximum fitness value, 7, will be returned. This element is selected as parent and its fitness values is replaced by -999999999 to avoid selecting it again. The next list becomes as follows:
[5, 2, -999999999, 1, 3, 1]
Next is to select the next solution with the highest fitness value. This is the solution with fitness value 5 (first element). It will be selected and its value is replaced by -999999999 to avoid selecting it again. Note that if the value 7 is left without being replaced by -999999999 then it will be selected again. That is the same parent is selected **twice**.
[-999999999, 2, -999999999, 1, 3, 1]
The process repeats itself until selecting the number of parents required.
Wish that helps.

**Comment by adilahrashid** [comment]
Hi,
It's all clear now, thank you!

**Comment by adilahrashid** [comment]
Hi! Another question if you don't mind.
May I know why pop_weight_mat is in object dtype? Why isn't in float?
Does it has to be object? I try to see the shape of pop_weight_mat is (8,3) but when I print out the matrix, it produces a lots of numbers more than (8,3). What is this actually?

**Comment by ahmedfgad** [comment]
The **pop_weights_mat** is a NumPy array in which its children are arrays. In other ways, it is an array of arrays. The child arrays represent the weights of the ANN layers. Because the children of this array are actually arrays not numeric values, the **dtype** is set to **object**.

The shape of the **pop_weights_mat** array is:
`pop_weights_mat.shape
Out: (8, 3)`

The **pop_weights_mat** array holds the ANN layer weights for 8 solutions. For each solution, there are 3 subarrays. If the dtype of a subarray is printed, it will be float:
`pop_weights_mat[0, 0].dtype
Out: dtype('float64')`

This answers your first question. It also helps answering the second question. The shape (8, 3) does not mean that there are 8x3=24 elements only. This is because the number 3 represents 3 child arrays. The shape of these arrays are as follows:
`pop_weights_mat[0, 0].shape
Out: (102, 150)`

`pop_weights_mat[0, 1].shape
Out: (150, 60)`

`pop_weights_mat[0, 2].shape
Out: (60, 4)`

Thus the total number of elements within the array is:
`8*(102*150+150*60+60*4)
Out: 196320`

Wish that helps.

**Comment by adilahrashid** [comment]
Hi Ahmed,
>
>
> Thank you very  much for your instant reply. Im actually referring to your
> code for optimizing GA with RNN, that i used library tensorlfow. Everything
> is great but when i try to compute the fitness , fitness=
> fitness(pop_weights_mat, train_X, train_y), some error raised. It is Value
> error: setting an array element with a sequence. The error is appointed at
> a line in tensorflow which says nparray=
> values.astype(dtype.as_numpy_dtype) which i believe it asks to change to
> numpy dtype. So i tried to change pop_weights_mat to np.object and the
> error is still the same. I did googling , some say the error is due to the
> cramping of values into an array or mismatch of size. I did check you data
> inputs (1962, 360) and data outputs (1962,). The shape of input and output
> is matched. But when i check on pop_weights_mat (8,3)  that due to 8
> solutions with 3 subarrays, i dont get it. it seems like pop_weights_mat
> doesnt match to any input or output. Thus i cannot figure out on how to
> adjust this on my dataset. Fyi, my train_X ( 238469,1,8) and train_y (
> 238469). I have 1 input, hidden and output layer only. Do you have any idea
> how i can compute my pop_weights_mat? Any example would do.



Thank you very much.

**Comment by ahmedfgad** [comment]
pop_weights_mat holds the weights of the entire network, layer by layer. You have to prepare the weights of the network in a single array and be able to extract the weights again from this array.

I am sure that the error is somewhere in feeding/extracting the network weights to this variable but I can not figure out the exact reason for such an error.

**Comment by adilahrashid** [comment]
Hi Ahmed, its me again.

I understand that pop_weights_mat holds weight for entire network, hence it
is a list. I tried to extract the shape of my model weight, it is a list of
5 arrays( 5,), first 3 arrays are for the input-hidden layer and the 2 last
arrays are for the hidden-output layer.

[array([[-0.32665274, -0.07861078, -0.46744072, -0.52869594],
        [ 0.3600487 ,  0.59808725, -0.6770948 ,  0.57669955],
        [-0.5771697 ,  0.19524729,  0.14795971, -0.36453515],
        [-0.609599  , -0.35582104, -0.29285517,  0.5004768 ],
        [ 0.3328982 , -0.22987211, -0.56666034, -0.54277384],
        [-0.41561934,  0.01080579,  0.17472953, -0.6253173 ],
        [ 0.17905009,  0.29364783, -0.60845363, -0.20369118],
        [-0.253413  ,  0.01676905, -0.24758187,  0.212233  ]],
       dtype=float32),
 array([[-0.3870803 , -0.65903616, -0.47994772,  0.4306859 ]],
       dtype=float32),
 array([0., 1., 0., 0.], dtype=float32),
 array([[-0.23260951]], dtype=float32),
 array([0.], dtype=float32)]

However, when i try to convert the matrix into vector i got error says;
line 17, in mat_to_vector
    for layer_idx in range(mat_pop_weights.shape[1]):

IndexError: tuple index out of range

which i believe its due to the shape of my matrix which is (5,) meanwhile
yours is (8,3). I cannot change this shape as this is the only shape that
my model (keras) accept. Do you have any idea on how to adjust
mat_to_vector to suit this shape?

Thank you very much for your constant help 😄

**Comment by Amaahmed** [comment]
Hello Ahmed,
Great job done. Quick question, do you happen to have a MATLAB version of this code? Thanks

**Comment by ahmedfgad** [comment]
Hi dear,
Sorry for the late reply.
No. I did not implement GA in MATLAB. But you can map the Python code to its equivalent in MATLAB and it will not be tiresome [I think].
